### ISSUE TITLE
logstash UDP listener died ()

### ISSUE THREAD

**Issue by AJNOURI** [AJNOURI/elk-stuff#7]
> 16:08:17.319 [[main]<udp] WARN  logstash.inputs.udp - UDP listener died {:exception=>#<NameError: uninitialized constant LogStash::Inputs::Udp::IPAddr>, :backtrace=>["org/jruby/RubyModule.java:2746:in `const_missing'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:87:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:57:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:470:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:463:in `start_input'"]}

using very simple config:

```
input {
    udp {
        port => 5001
        type => "cisco"
    }

}

filter {
}

output {
    stdout {
        codec => rubydebug
    }
}
```

`# logstash -f  mylogstash/config-dir/cisco.conf -r`

**Comment by AJNOURI** [comment]
Updating udp plugin solved the same issue:

```
# logstash-plugin update logstash-input-udp
Updating logstash-input-udp
Updated logstash-input-udp 3.3.1 to 3.3.3
```
