### ISSUE TITLE
Logstash Flapping listener: logstash.inputs.udp - Starting UDP listener {:address=>"0.0.0.0:5001"} ... logstash.inputs.udp - UDP listener died

### ISSUE THREAD

**Issue by AJNOURI** [AJNOURI/elk-stuff#8]
I am trying to listen to udp port 5001, but the process is flapping

> 16:34:33.991 [[main]<udp] INFO  logstash.inputs.udp - Starting UDP listener {:address=>"0.0.0.0:5001"}
> 16:34:33.992 [[main]<udp] WARN  logstash.inputs.udp - UDP listener died {:exception=>#<NameError: uninitialized constant LogStash::Inputs::Udp::IPAddr>, :backtrace=>["org/jruby/RubyModule.java:2746:in `const_missing'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:87:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:57:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:470:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:463:in `start_input'"]}

> 16:34:38.992 [[main]<udp] INFO  logstash.inputs.udp - Starting UDP listener {:address=>"0.0.0.0:5001"}
> 16:34:38.993 [[main]<udp] WARN  logstash.inputs.udp - UDP listener died {:exception=>#<NameError: uninitialized constant LogStash::Inputs::Udp::IPAddr>, :backtrace=>["org/jruby/RubyModule.java:2746:in `const_missing'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:87:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:57:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:470:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:463:in `start_input'"]}
> 16:34:43.995 [[main]<udp] INFO  logstash.inputs.udp - Starting UDP listener {:address=>"0.0.0.0:5001"}

> 16:34:43.996 [[main]<udp] WARN  logstash.inputs.udp - UDP listener died {:exception=>#<NameError: uninitialized constant LogStash::Inputs::Udp::IPAddr>, :backtrace=>["org/jruby/RubyModule.java:2746:in `const_missing'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:87:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:57:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:470:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:463:in `start_input'"]}

It is talking about  NameError: uninitialized constant LogStash::Inputs::Udp::IPAddr (constant missing)
Tried setting the host:

     udp {
     port => 5001
     host => "51.15.239.154"
     type => "cisco"
     }

still the same outcome

    16:37:37.844 [[main]<udp] INFO  logstash.inputs.udp - Starting UDP listener {:address=>"51.15.239.154:5001"}
    16:37:37.845 [[main]<udp] WARN  logstash.inputs.udp - UDP listener died {:exception=>#<NameError: uninitialized constant LogStash::Inputs::Udp::IPAddr>, :backtrace=>["org/jruby/RubyModule.java:2746:in `const_missing'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:87:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:57:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:470:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:463:in `start_input'"]}

    16:37:42.848 [[main]<udp] INFO  logstash.inputs.udp - Starting UDP listener {:address=>"51.15.239.154:5001"}
    16:37:42.849 [[main]<udp] WARN  logstash.inputs.udp - UDP listener died {:exception=>#<NameError: uninitialized constant LogStash::Inputs::Udp::IPAddr>, :backtrace=>["org/jruby/RubyModule.java:2746:in `const_missing'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:87:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.3.1/lib/logstash/inputs/udp.rb:57:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:470:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:463:in `start_input'"]}
    16:37:47.849 [[main]<udp] INFO  logstash.inputs.udp - Starting UDP listener {:address=>"51.15.239.154:5001"}

-------------
I am running ELK stack on containers with **docker-compose**:

    root@scw-1f59eb:~# docker-compose ps
                Name                         Command                         State                          Ports             
    -------------------------------------------------------------------------------------------------------------------------
    root_elasticsearch_1           /docker-entrypoint.sh elas     Up                             0.0.0.0:9200->9200/tcp,      
                                   ...                                                           0.0.0.0:9300->9300/tcp       
    root_kibana_1                  /docker-entrypoint.sh kibana   Up                             0.0.0.0:5601->5601/tcp       
    root_mylogstash_1              /docker-entrypoint.sh bash     Up                             0.0.0.0:5000->5000/tcp,      
                                                                                                 0.0.0.0:5000->5000/udp,      
                                                                                                 0.0.0.0:514->514/tcp,        
                                                                                                 0.0.0.0:514->514/udp,        
                                                                                                 0.0.0.0:8080->8080/tcp       

using the following **docker-compose** file:

    version: '2'
    services:
        elasticsearch:
            image: elasticsearch
            ports:
                - "9200:9200"
                - "9300:9300"
            volumes:
                - ./data:/usr/share/elasticsearch/data
        mylogstash:
            build:
                context: .
                dockerfile: Dockerfile
            volumes:
                - ./config-dir:/mylogstash/config-dir:rw
                - ./data:/mylogstash/data:rw
                - ./plugin:/mylogstash/plugin:rw
            ports:
                - "5000:5000/tcp"
                - "5000:5000/udp"
                - "8080:8080"
                - "514:514/udp"
                - "514:514/tcp"
            tty: true
            command: ["bash"]
            links:
                - elasticsearch
        kibana:
            image: kibana
            ports:
                - "5601:5601"
            links:
                - elasticsearch

**Comment by AJNOURI** [comment]
I have configured logstash to listen to port udp 5001, but docker-compose ports for logstash is not configured for port 5001.

**docker-compose:**
```
        ports:
            - "5000:5000/tcp"
            - "5000:5000/udp"
            - "8080:8080"
            - "514:514/udp"
            - "514:514/tcp"
```
logstash configuration:
```
 udp {
 port => 5001
 type => "cisco"
 }
```

as soon as I corrected to port from 5001 to 5000 it works fine.
```
 udp {
 port => 5000
 type => "cisco"
 }
```
Or I could also modify docker-compose to map logstash container port 5001 to local host port 5001
